import 'package:plato_gymapp/i18n/strings.g.dart';

extension DynamicTranslationX on Translations {
  /// Translates a key dynamically by converting it from snake_case to camelCase.
  /// This bridges the gap between literal keys in strings.i18n.json (like "rank.name_bronze_1")
  /// and the camelCase flat_map keys generated by slang (like "rank.nameBronze1").
  String translateDynamic(String key, {String? fallback}) {
    if (key.isEmpty) return fallback ?? key;
    
    // Slang is now configured to use snake_case, so the generated flat_map keys 
    // exactly match the JSON keys (e.g. "gamification.title_quest_1").
    // We no longer need to convert to camelCase.
    return this[key]?.toString() ?? fallback ?? key;
  }
}
