-- =========================================================================
-- WARM UP & FULL BODY
-- =========================================================================
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('d85332c1-01e4-4845-9d1d-bb814e36f7d2', 'exercises.name_warm_up', 'FULL_BODY', '[]', 'exercises.desc_warm_up', 'TIME_ONLY', 'BODYWEIGHT', '', '', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('dadedcf5-c336-41f4-951f-b78e053abafa', 'exercises.name_burpees', 'FULL_BODY', '["QUADS","MIDDLE_CHEST","FRONT_DELTS","TRICEPS","ABS"]', 'exercises.desc_burpees', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/burpees.webp', 'assets/exercises/burpees.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('45a788c4-f9d8-47f4-91e2-b881fb57728d', 'exercises.name_jumping_jacks', 'FULL_BODY', '["CALVES","SIDE_DELTS","ABS"]', 'exercises.desc_jumping_jacks', 'TIME_ONLY', 'BODYWEIGHT', 'assets/gifs/jumping_jacks.webp', 'assets/exercises/jumping_jacks.webp', 0);

-- =========================================================================
-- CHEST (NGỰC)
-- =========================================================================
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('048d702f-26c6-4e21-ae5e-bef75969dd12', 'exercises.name_decline_push_up', 'UPPER_CHEST', '["FRONT_DELTS","TRICEPS","ABS"]', 'exercises.desc_decline_push_up', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/decline_push_up.webp', 'assets/exercises/decline_push_up.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('0d186432-a941-4c10-989e-da1dc5cdde8c', 'exercises.name_incline_barbell_press', 'UPPER_CHEST', '["FRONT_DELTS","TRICEPS"]', 'exercises.desc_incline_barbell_press', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/incline_barbell_press.webp', 'assets/exercises/incline_barbell_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('3cd6e253-a663-45ed-90bb-1ed687aab21f', 'exercises.name_incline_dumbbell_fly', 'UPPER_CHEST', '["FRONT_DELTS"]', 'exercises.desc_incline_dumbbell_fly', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/incline_dumbell_chest_fly.webp', 'assets/exercises/incline_dumbell_chest_fly.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('fc0ba6d5-e012-4f95-a474-b042e69ceefd', 'exercises.name_incline_dumbbell_press', 'UPPER_CHEST', '["FRONT_DELTS","TRICEPS"]', 'exercises.desc_incline_dumbbell_press', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/incline_dumbbell_press.webp', 'assets/exercises/incline_dumbbell_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('508e26a0-5adc-485a-8114-256b9e878fcb', 'exercises.name_bench_press', 'MIDDLE_CHEST', '["FRONT_DELTS","TRICEPS"]', 'exercises.desc_bench_press', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/flat_bench_press.webp', 'assets/exercises/flat_bench_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('3422038b-5862-4c7f-944e-cc69cce8f6f9', 'exercises.name_dumbbell_bench_press', 'MIDDLE_CHEST', '["FRONT_DELTS","TRICEPS"]', 'exercises.desc_dumbbell_bench_press', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_bench_press.webp', 'assets/exercises/dumbbell_bench_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('65421940-c135-4cd3-a9b3-10878b1bac2a', 'exercises.name_dumbbell_fly', 'MIDDLE_CHEST', '["FRONT_DELTS"]', 'exercises.desc_dumbbell_fly', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_flyes.webp', 'assets/exercises/dumbbell_flyes.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('9f5b6da2-3720-420b-a7d6-0e45d82493eb', 'exercises.name_machine_chest_press', 'MIDDLE_CHEST', '["FRONT_DELTS","TRICEPS"]', 'exercises.desc_machine_chest_press', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/machine_chest_press.webp', 'assets/exercises/machine_chest_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a2280d84-ea7d-4f4c-9d36-8ddc98c8b35e', 'exercises.name_push_up', 'MIDDLE_CHEST', '["FRONT_DELTS","TRICEPS","ABS"]', 'exercises.desc_push_up', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/push_up.webp', 'assets/exercises/push_up.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('11111111-1111-4111-a111-111111111111', 'exercises.name_cable_crossover', 'LOWER_CHEST', '["FRONT_DELTS"]', 'exercises.desc_cable_crossover', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/cable_crossover.webp', 'assets/exercises/cable_crossover.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('55555555-5555-4555-a555-555555555555', 'exercises.name_pec_deck_fly', 'MIDDLE_CHEST', '["FRONT_DELTS"]', 'exercises.desc_pec_deck_fly', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/machine_pec_deck_fly.webp', 'assets/exercises/machine_pec_deck_fly.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('6dc5360e-8730-4006-a7ec-76bdb7333067', 'exercises.name_decline_bench_press', 'LOWER_CHEST', '["FRONT_DELTS","TRICEPS"]', 'exercises.desc_decline_bench_press', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/decline_bench_press.webp', 'assets/exercises/decline_bench_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a5088451-198b-4a23-8231-7f587c91aa45', 'exercises.name_chest_dips', 'LOWER_CHEST', '["FRONT_DELTS","TRICEPS"]', 'exercises.desc_chest_dips', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/chest_dips.webp', 'assets/exercises/chest_dips.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('5da74b33-ee77-42ee-ba1a-603d57bdc40e', 'exercises.name_low_to_high_fly', 'UPPER_CHEST', '["FRONT_DELTS"]', 'exercises.desc_low_to_high_fly', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/low_to_high_cable_fly.webp', 'assets/exercises/low_to_high_cable_fly.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('393e1425-a901-43b9-80d3-a4b7f12bc624', 'exercises.name_incline_push_up', 'LOWER_CHEST', '["FRONT_DELTS","TRICEPS","ABS"]', 'exercises.desc_incline_push_up', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/incline_push_up.webp', 'assets/exercises/incline_push_up.webp', 0);

-- =========================================================================
-- BACK (LƯNG)
-- =========================================================================
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('e43fbff4-565a-413f-8e1f-77d7a1bac160', 'exercises.name_close_grip_pulldown', 'LATS', '["BICEPS","FOREARMS","UPPER_BACK"]', 'exercises.desc_close_grip_pulldown', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/close_grip_lat_pulldown.webp', 'assets/exercises/close_grip_lat_pulldown.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('d41fb318-8384-48f7-9b98-b478b1db7195', 'exercises.name_lat_pulldown', 'LATS', '["BICEPS","FOREARMS","UPPER_BACK"]', 'exercises.desc_lat_pulldown', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/lat_pulldown.webp', 'assets/exercises/lat_pulldown.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('5c4e20d3-53ad-484b-aca5-c1276edb8146', 'exercises.name_one_arm_row', 'LATS', '["UPPER_BACK","BICEPS","FOREARMS","REAR_DELTS"]', 'exercises.desc_one_arm_row', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/one_arm_dumbbell_row.webp', 'assets/exercises/one_arm_dumbbell_row.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('ff24e899-1f8a-4b22-871b-531c4b3ecc73', 'exercises.name_pull_up', 'LATS', '["UPPER_BACK","BICEPS","FOREARMS"]', 'exercises.desc_pull_up', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/pull_up.webp', 'assets/exercises/pull_up.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('be7244b3-aa99-4e5b-ad9d-74ebb4d654e6', 'exercises.name_australian_pull_up', 'UPPER_BACK', '["LATS","BICEPS","FOREARMS","REAR_DELTS"]', 'exercises.desc_australian_pull_up', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/australian_pull_up.webp', 'assets/exercises/australian_pull_up.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('bade7b92-d6b0-4b2f-84cd-e65d9a89d7d9', 'exercises.name_barbell_row', 'UPPER_BACK', '["LATS","LOWER_BACK","BICEPS","FOREARMS","REAR_DELTS"]', 'exercises.desc_barbell_row', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/barbell_row.webp', 'assets/exercises/barbell_row.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('dae37013-80ab-43df-b632-1df0a136b794', 'exercises.name_dumbbell_row', 'UPPER_BACK', '["LATS","BICEPS","FOREARMS","REAR_DELTS"]', 'exercises.desc_dumbbell_row', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_bent_over.webp', 'assets/exercises/dumbbell_bent_over.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('e48e9a3e-5bbd-470c-9440-920787de5087', 'exercises.name_seated_cable_row_vgrip', 'UPPER_BACK', '["LATS","BICEPS","FOREARMS"]', 'exercises.desc_seated_cable_row_vgrip', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/seated_cable_row_vgrip.webp', 'assets/exercises/seated_cable_row_vgrip.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('e48e9a3e-5bbd-470c-9440-920787de5088', 'exercises.name_seated_cable_row_widegrip', 'UPPER_BACK', '["LATS","BICEPS","FOREARMS","REAR_DELTS"]', 'exercises.desc_seated_cable_row_widegrip', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/seated_cable_row_widegrip.webp', 'assets/exercises/seated_cable_row_widegrip.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('22222222-2222-4222-a222-222222222222', 'exercises.name_t_bar_row', 'UPPER_BACK', '["LATS","LOWER_BACK","BICEPS","FOREARMS"]', 'exercises.desc_t_bar_row', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/machine_t_bar_row.webp', 'assets/exercises/machine_t_bar_row.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('9e449cdb-78c4-4f9c-baeb-147a1c603013', 'exercises.name_deadlift', 'LOWER_BACK', '["GLUTES","HAMSTRINGS","QUADS","FOREARMS","TRAPS"]', 'exercises.desc_deadlift', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/deadlift_truyen_thong.webp', 'assets/exercises/deadlift_truyen_thong.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('95044ae2-30bf-4c74-8568-1d97bf67514b', 'exercises.name_dumbbell_deadlift', 'LOWER_BACK', '["GLUTES","HAMSTRINGS","FOREARMS","TRAPS"]', 'exercises.desc_dumbbell_deadlift', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_deadlift.webp', 'assets/exercises/dumbbell_deadlift.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('b19571dc-57f2-488e-9ce0-883605f3fa86', 'exercises.name_hyperextensions', 'LOWER_BACK', '["GLUTES","HAMSTRINGS"]', 'exercises.desc_hyperextensions', 'WEIGHT_REPS', 'BODYWEIGHT', 'assets/gifs/hyperextensions.webp', 'assets/exercises/hyperextensions.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('d530ca20-9f5c-4374-876e-3ca436abdd93', 'exercises.name_superman', 'LOWER_BACK', '["GLUTES","HAMSTRINGS"]', 'exercises.desc_superman', 'TIME_ONLY', 'BODYWEIGHT', 'assets/gifs/superman.webp', 'assets/exercises/superman.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-3333-4a1b-8c2d-123456789003', 'exercises.name_chest_supported_row', 'UPPER_BACK', '["LATS","BICEPS","FOREARMS","REAR_DELTS"]', 'exercises.desc_chest_supported_row', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_chest_support_row.webp', 'assets/exercises/dumbbell_chest_support_row.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-4444-4a1b-8c2d-123456789004', 'exercises.name_single_arm_lat_pulldown', 'LATS', '["BICEPS","FOREARMS","UPPER_BACK"]', 'exercises.desc_single_arm_lat_pulldown', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/cable_one_arm_lat_pulldown.webp', 'assets/exercises/cable_one_arm_lat_pulldown.webp', 0);

-- =========================================================================
-- SHOULDERS (VAI)
-- =========================================================================
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('4b12db95-76eb-4efb-87cf-1f03ff88886e', 'exercises.name_arnold_press', 'FRONT_DELTS', '["SIDE_DELTS","TRICEPS"]', 'exercises.desc_arnold_press', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/arnold_press.webp', 'assets/exercises/arnold_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a8922fc8-2235-4181-b637-2e2af59de8f9', 'exercises.name_overhead_press', 'FRONT_DELTS', '["SIDE_DELTS","TRICEPS"]', 'exercises.desc_overhead_press', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/barbell_overhead_press.webp', 'assets/exercises/barbell_overhead_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('ca8e4db1-4db2-4aca-84e5-c27e1f8d1985', 'exercises.name_dumbbell_shoulder_press', 'FRONT_DELTS', '["SIDE_DELTS","TRICEPS"]', 'exercises.desc_dumbbell_shoulder_press', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_shoulder_press.webp', 'assets/exercises/dumbbell_shoulder_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('3518b81c-a6e8-4dcc-a948-29c5c12ef36c', 'exercises.name_pike_push_up', 'FRONT_DELTS', '["TRICEPS","UPPER_CHEST"]', 'exercises.desc_pike_push_up', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/pike_push_up.webp', 'assets/exercises/pike_push_up.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('b0abae7a-09f7-4ee4-83a3-ac1c9d5a53ba', 'exercises.name_cable_lateral_raise', 'SIDE_DELTS', '["TRAPS"]', 'exercises.desc_cable_lateral_raise', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/cable_lateral_raise.webp', 'assets/exercises/cable_lateral_raise.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('5a023679-9325-4540-954b-b0f13133588c', 'exercises.name_dumbbell_lateral_raise', 'SIDE_DELTS', '["TRAPS"]', 'exercises.desc_dumbbell_lateral_raise', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_lateral_raise.webp', 'assets/exercises/dumbbell_lateral_raise.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('f38ab095-d21a-4757-9fa8-ae4f0f51afca', 'exercises.name_upright_row', 'SIDE_DELTS', '["TRAPS","BICEPS"]', 'exercises.desc_upright_row', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/upright_row.webp', 'assets/exercises/upright_row.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('4a4483c5-c227-4e86-96d6-99b93b80fb48', 'exercises.name_dumbbell_reverse_fly', 'REAR_DELTS', '["UPPER_BACK","TRAPS"]', 'exercises.desc_dumbbell_reverse_fly', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_reverse_fly.webp', 'assets/exercises/dumbbell_reverse_fly.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('9c3feaab-d131-4ef8-8e50-9dfa217a8cd3', 'exercises.name_face_pull', 'REAR_DELTS', '["UPPER_BACK","TRAPS"]', 'exercises.desc_face_pull', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/face_pull.webp', 'assets/exercises/face_pull.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('0b84ef74-fcab-4ff8-9084-b50e4d3732c3', 'exercises.name_reverse_pec_deck', 'REAR_DELTS', '["UPPER_BACK","TRAPS"]', 'exercises.desc_reverse_pec_deck', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/reverse_pec_deck.webp', 'assets/exercises/reverse_pec_deck.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('fc6651e0-062a-43d8-ad3b-99f90b2370bc', 'exercises.name_dumbbell_shrugs', 'TRAPS', '["FOREARMS"]', 'exercises.desc_dumbbell_shrugs', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_shrugs.webp', 'assets/exercises/dumbbell_shrugs.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-9999-4a1b-8c2d-123456789009', 'exercises.name_shoulder_press_machine', 'FRONT_DELTS', '["SIDE_DELTS","TRICEPS"]', 'exercises.desc_shoulder_press_machine', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/machine_shoulder_press.webp', 'assets/exercises/machine_shoulder_press.webp', 0);

-- =========================================================================
-- ARMS (TAY & CẲNG TAY)
-- =========================================================================
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('e8a9a1fb-920d-4b44-a0f4-c383ae2841b9', 'exercises.name_barbell_curl', 'BICEPS', '["FOREARMS"]', 'exercises.desc_barbell_curl', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/barbell_bicep_curl.webp', 'assets/exercises/barbell_bicep_curl.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('3422da8e-b1ad-4e56-9478-74888f491c65', 'exercises.name_chin_up', 'BICEPS', '["LATS","FOREARMS"]', 'exercises.desc_chin_up', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/chin_up.webp', 'assets/exercises/chin_up.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('82ed3c39-e58f-4b9f-aa14-89354ed46d04', 'exercises.name_dumbbell_curl', 'BICEPS', '["FOREARMS"]', 'exercises.desc_dumbbell_curl', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_curl.webp', 'assets/exercises/dumbbell_curl.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('b9558187-4ed6-46e0-b2c9-cfbb6127b4a6', 'exercises.name_hammer_curl', 'BICEPS', '["FOREARMS"]', 'exercises.desc_hammer_curl', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/hammer_curl.webp', 'assets/exercises/hammer_curl.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('44444444-4444-4444-a444-444444444444', 'exercises.name_preacher_curl', 'BICEPS', '["FOREARMS"]', 'exercises.desc_preacher_curl', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/barbell_preacher_curl.webp', 'assets/exercises/barbell_preacher_curl.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('0d109cfd-2936-498c-b5b8-c38d3a30f892', 'exercises.name_bench_dips', 'TRICEPS', '["FRONT_DELTS","LOWER_CHEST"]', 'exercises.desc_bench_dips', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/bench_dips.webp', 'assets/exercises/bench_dips.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('14302a59-3b62-4d00-92ee-9de37fe62d1d', 'exercises.name_diamond_push_up', 'TRICEPS', '["MIDDLE_CHEST","FRONT_DELTS"]', 'exercises.desc_diamond_push_up', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/diamond_push_up.webp', 'assets/exercises/diamond_push_up.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('7b0d0cb4-cf83-4a5a-988d-29c8e91baf13', 'exercises.name_overhead_triceps_extension', 'TRICEPS', '[]', 'exercises.desc_overhead_triceps_extension', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/overhead_triceps_extension.webp', 'assets/exercises/overhead_triceps_extension.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('917be2f9-7589-4c20-a53e-240256b2bfd1', 'exercises.name_skull_crushers', 'TRICEPS', '[]', 'exercises.desc_skull_crushers', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/skull_crushers.webp', 'assets/exercises/skull_crushers.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('99365bca-e3e2-4dde-9644-340ce03da818', 'exercises.name_tricep_pushdown', 'TRICEPS', '[]', 'exercises.desc_tricep_pushdown', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/tricep_pushdown.webp', 'assets/exercises/tricep_pushdown.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-1111-4a1b-8c2d-123456789001', 'exercises.name_overhead_cable_triceps', 'TRICEPS', '[]', 'exercises.desc_overhead_cable_triceps', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/overhead_cable_triceps.webp', 'assets/exercises/overhead_cable_triceps.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-2222-4a1b-8c2d-123456789002', 'exercises.name_seated_wrist_curl', 'FOREARMS', '[]', 'exercises.desc_seated_wrist_curl', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/barbell_seated_wrist_curl.webp', 'assets/exercises/barbell_seated_wrist_curl.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-8888-4a1b-8c2d-123456789008', 'exercises.name_seated_incline_curl', 'BICEPS', '["FOREARMS"]', 'exercises.desc_seated_incline_curl', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_incline_biceps_curl.webp', 'assets/exercises/dumbbell_incline_biceps_curl.webp', 0);

-- =========================================================================
-- CORE (BỤNG & LIÊN SƯỜN)
-- =========================================================================
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('0824045c-64a5-40af-aa50-8063282ace68', 'exercises.name_cable_crunch', 'ABS', '["OBLIQUES"]', 'exercises.desc_cable_crunch', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/cable_crunch.webp', 'assets/exercises/cable_crunch.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('e4cda12e-8ea0-4465-8f95-eec063c38ce1', 'exercises.name_crunch', 'ABS', '["OBLIQUES"]', 'exercises.desc_crunch', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/crunch.webp', 'assets/exercises/crunch.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('1677ac52-6281-4de1-85bd-0d0c83282263', 'exercises.name_hanging_leg_raise', 'ABS', '["HIP_FLEXORS","OBLIQUES"]', 'exercises.desc_hanging_leg_raise', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/hanging_leg_raise.webp', 'assets/exercises/hanging_leg_raise.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('ef3af3da-90e2-40aa-adf8-beda1af2cb06', 'exercises.name_lying_leg_raise', 'ABS', '["HIP_FLEXORS"]', 'exercises.desc_lying_leg_raise', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/lying_leg_raise.webp', 'assets/exercises/lying_leg_raise.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('c4ed4325-1172-4461-bba3-20f6874cbe84', 'exercises.name_mountain_climbers', 'ABS', '["HIP_FLEXORS","FRONT_DELTS","OBLIQUES"]', 'exercises.desc_mountain_climbers', 'TIME_ONLY', 'BODYWEIGHT', 'assets/gifs/mountain_climbers.webp', 'assets/exercises/mountain_climbers.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('604df66b-057d-413f-8d06-02559815bdbc', 'exercises.name_plank', 'ABS', '["OBLIQUES"]', 'exercises.desc_plank', 'TIME_ONLY', 'BODYWEIGHT', '', 'assets/exercises/plank.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('b9d26065-e9bc-41ce-8e52-ce8ac5ddc393', 'exercises.name_bicycle_crunches', 'OBLIQUES', '["ABS","HIP_FLEXORS"]', 'exercises.desc_bicycle_crunches', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/bicycle_crunches.webp', 'assets/exercises/bicycle_crunches.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('cca38797-cdf4-463a-8942-1d56d9356412', 'exercises.name_russian_twist', 'OBLIQUES', '["ABS"]', 'exercises.desc_russian_twist', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/russian_twist.webp', 'assets/exercises/russian_twist.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-0000-4a1b-8c2d-123456789010', 'exercises.name_crunch_machine', 'ABS', '["OBLIQUES"]', 'exercises.desc_crunch_machine', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/machine_crunch.webp', 'assets/exercises/machine_crunch.webp', 0);

-- =========================================================================
-- LEGS (CHÂN, ĐÙI, MÔNG, BẮP CHÂN)
-- =========================================================================
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('ec90bdf1-c111-4613-84ba-fc152acffe60', 'exercises.name_squat', 'QUADS', '["GLUTES","HAMSTRINGS"]', 'exercises.desc_squat', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/air_squat.webp', 'assets/exercises/air_squat.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('f3e5a775-5fc7-4d2b-bf67-ece1d8ee18bc', 'exercises.name_barbell_squat', 'QUADS', '["GLUTES","HAMSTRINGS","LOWER_BACK","CALVES"]', 'exercises.desc_barbell_squat', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/barbell_squat.webp', 'assets/exercises/barbell_squat.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('ea41efeb-f94f-4c67-9666-29b865a487f8', 'exercises.name_bulgarian_split_squat', 'QUADS', '["GLUTES","HAMSTRINGS"]', 'exercises.desc_bulgarian_split_squat', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/bulgarian_split_squat.webp', 'assets/exercises/bulgarian_split_squat.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('f4e80cc1-970a-4558-8ca6-d6c4679ac1fe', 'exercises.name_dumbbell_lunges', 'QUADS', '["GLUTES","HAMSTRINGS"]', 'exercises.desc_dumbbell_lunges', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_lunges.webp', 'assets/exercises/dumbbell_lunges.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('fb86219b-df55-4ff2-a887-7936339c0b77', 'exercises.name_goblet_squat', 'QUADS', '["GLUTES","HAMSTRINGS","LOWER_BACK"]', 'exercises.desc_goblet_squat', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_goblet_squat.webp', 'assets/exercises/dumbbell_goblet_squat.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('8cf8c398-24e1-4001-996f-b2bfffd2743b', 'exercises.name_leg_extension', 'QUADS', '[]', 'exercises.desc_leg_extension', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/leg_extension.webp', 'assets/exercises/leg_extension.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('414e7822-27e7-454b-9315-3eac5310ecd3', 'exercises.name_leg_press', 'QUADS', '["GLUTES","HAMSTRINGS"]', 'exercises.desc_leg_press', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/leg_press.webp', 'assets/exercises/leg_press.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('33333333-3333-4333-a333-333333333333', 'exercises.name_hack_squat', 'QUADS', '["GLUTES","HAMSTRINGS"]', 'exercises.desc_hack_squat', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/machine_hack_squat.webp', 'assets/exercises/machine_hack_squat.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('f29bb1ee-67df-448d-804f-3474c0a63f7e', 'exercises.name_dumbbell_rdl', 'HAMSTRINGS', '["GLUTES","LOWER_BACK","FOREARMS"]', 'exercises.desc_dumbbell_rdl', 'WEIGHT_REPS', 'DUMBBELL', 'assets/gifs/dumbbell_romanian_deadlift.webp', 'assets/exercises/dumbbell_romanian_deadlift.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('58f4ef16-98c0-4e2c-b8a1-0b009c56a4f0', 'exercises.name_lying_leg_curl', 'HAMSTRINGS', '["CALVES"]', 'exercises.desc_lying_leg_curl', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/lying_leg_curl.webp', 'assets/exercises/lying_leg_curl.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a67467c2-3c5e-4f64-8cb0-e9a203e4d07c', 'exercises.name_romanian_deadlift', 'HAMSTRINGS', '["GLUTES","LOWER_BACK","FOREARMS"]', 'exercises.desc_romanian_deadlift', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/romanian_deadlift.webp', 'assets/exercises/romanian_deadlift.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('66666666-6666-4666-a666-666666666666', 'exercises.name_seated_leg_curl', 'HAMSTRINGS', '["CALVES"]', 'exercises.desc_seated_leg_curl', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/machine_seated_leg_curl.webp', 'assets/exercises/machine_seated_leg_curl.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('18724e3a-530d-4b92-b2d4-35ee8fbe25c6', 'exercises.name_hip_thrust', 'GLUTES', '["HAMSTRINGS"]', 'exercises.desc_hip_thrust', 'WEIGHT_REPS', 'BARBELL', 'assets/gifs/hip_thrust.webp', 'assets/exercises/hip_thrust.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('e459fad7-fd37-42f8-96eb-a1efe1a12473', 'exercises.name_cable_kickback', 'GLUTES', '["HAMSTRINGS"]', 'exercises.desc_cable_kickback', 'WEIGHT_REPS', 'CABLE', 'assets/gifs/cable_kickback.webp', 'assets/exercises/cable_kickback.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('44458889-234d-4df3-93e0-449272a20413', 'exercises.name_glute_bridge', 'GLUTES', '["HAMSTRINGS"]', 'exercises.desc_glute_bridge', 'REPS_ONLY', 'BODYWEIGHT', 'assets/gifs/glute_bridge.webp', 'assets/exercises/glute_bridge.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('dd36ebd9-005f-47a6-8a06-dfb22bc10bd4', 'exercises.name_seated_calf_raise', 'CALVES', '[]', 'exercises.desc_seated_calf_raise', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/seated_calf_raise.webp', 'assets/exercises/seated_calf_raise.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('12173a58-7624-42bb-a69f-903f1666fd4f', 'exercises.name_standing_calf_raise', 'CALVES', '[]', 'exercises.desc_standing_calf_raise', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/standing_calf_raise.webp', 'assets/exercises/standing_calf_raise.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-5555-4a1b-8c2d-123456789005', 'exercises.name_smith_machine_squat', 'QUADS', '["GLUTES","HAMSTRINGS","CALVES"]', 'exercises.desc_smith_machine_squat', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/smith_machine_squat.webp', 'assets/exercises/smith_machine_squat.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-6666-4a1b-8c2d-123456789006', 'exercises.name_hip_adduction', 'ADDUCTORS', '[]', 'exercises.desc_hip_adduction', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/machine_hip_adduction.webp', 'assets/exercises/machine_hip_adduction.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a1b2c3d4-7777-4a1b-8c2d-123456789007', 'exercises.name_hip_abduction', 'ABDUCTORS', '["GLUTES"]', 'exercises.desc_hip_abduction', 'WEIGHT_REPS', 'MACHINE', 'assets/gifs/machine_hip_abduction.webp', 'assets/exercises/machine_hip_abduction.webp', 0);

-- =========================================================================
-- CARDIO
-- =========================================================================
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('6b05600c-d90c-49e4-b7bc-76a65fdcbe7b', 'exercises.name_indoor_cycling', 'CARDIO', '["QUADS","CALVES","GLUTES"]', 'exercises.desc_indoor_cycling', 'TIME_ONLY', 'MACHINE', 'assets/gifs/indoor_cycling.webp', 'assets/exercises/indoor_cycling.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('16e6b6a7-c9a3-4d5e-a10b-9355914620c4', 'exercises.name_high_knees', 'CARDIO', '["ABS","QUADS","CALVES"]', 'exercises.desc_high_knees', 'TIME_ONLY', 'BODYWEIGHT', 'assets/gifs/high_knees.webp', 'assets/exercises/high_knees.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('a3eca085-d03f-4eab-8f88-93e4a0c24166', 'exercises.name_jump_rope', 'CARDIO', '["CALVES"]', 'exercises.desc_jump_rope', 'TIME_ONLY', 'ROPE', 'assets/gifs/jump_rope.webp', 'assets/exercises/jump_rope.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('aaa1a546-7912-4632-9574-4e5cf05b249e', 'exercises.name_stair_climber', 'CARDIO', '["GLUTES","QUADS","CALVES"]', 'exercises.desc_stair_climber', 'CARDIO_STEPS', 'MACHINE', '', 'assets/exercises/stair_climber.webp', 0);
INSERT INTO exercises (id, name, primary_muscle, secondary_muscles, instructions, type, equipment, url_instructions, image, is_deleted) VALUES ('e0f0dc0b-3ba7-4ea8-91a7-2d6f95993f7f', 'exercises.name_treadmill', 'CARDIO', '["QUADS","CALVES","HAMSTRINGS","GLUTES"]', 'exercises.desc_treadmill', 'CARDIO_DISTANCE', 'MACHINE', '', 'assets/exercises/treadmil_running.webp', 0);


-- =========================================================================
-- FOODS
-- =========================================================================
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('09c4ecc7-a39a-4392-9782-0cce2d3e1324', 'nutrition.food_name_iced_coffee', 70, 1, 12, 2, 'ML', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('2045475e-5016-4ccd-8243-ea2bf091eb5d', 'nutrition.food_name_banh_mi', 440, 16, 52, 18, 'QUANTITY', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('445ea9bd-3792-4c57-a8a4-a8f3163f9df0', 'nutrition.food_name_com_tam', 640, 30, 80, 22, 'SERVING', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('45c2c6d1-06ce-4021-8336-9337c6a144c1', 'nutrition.food_name_pho_bo', 440, 22, 55, 14, 'SERVING', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('6cad74cd-26a9-45f3-9abf-a598b5f1ccf9', 'nutrition.food_name_fried_egg', 100, 6, 1, 8, 'QUANTITY', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('8325b4a7-8bb0-4ae6-a40b-e2a00bcf7046', 'nutrition.food_name_white_rice', 130, 3, 28, 0, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('9d93d70b-4908-4ec9-be64-52eab505e4e7', 'nutrition.food_name_avocado_smoothie', 150, 2, 16, 9, 'ML', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('c2bc073d-4c63-4470-8f98-05f76b94b5cf', 'nutrition.food_name_boiled_chicken_breast', 165, 31, 0, 4, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('c9e7392b-7da6-4926-8c55-736a5c9e30eb', 'nutrition.food_name_fresh_milk', 62, 3, 5, 3, 'ML', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('cec4b686-d952-4e99-91ca-bcec0d7ee691', 'nutrition.food_name_beef_tenderloin', 240, 26, 0, 15, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('ecd7ec0c-fccd-4512-b5db-a6178714664e', 'nutrition.food_name_bun_cha', 520, 20, 65, 20, 'SERVING', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('f3a24b57-e8d2-42e2-b982-78ea0703041b', 'nutrition.food_name_goi_cuon', 65, 4, 10, 1, 'QUANTITY', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('1e8c7b60-c3b2-4d29-a12f-871ab93f0b2f', 'nutrition.food_name_banana', 89, 1, 23, 0, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('9f8d7c50-b2a1-3c28-912e-761bc82e1a3e', 'nutrition.food_name_sweet_potato', 86, 2, 20, 0, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('2a7b6c50-d1e2-4f39-812d-651de72f2b4d', 'nutrition.food_name_oatmeal_raw', 389, 17, 66, 7, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('3b8c7d60-e2f3-5a40-923e-762ef83g3c5e', 'nutrition.food_name_apple', 52, 0, 14, 0, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('4c9d8e70-f3g4-6b51-034f-873fg94h4d6f', 'nutrition.food_name_whey_protein', 120, 24, 3, 1, 'SERVING', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('5d0e9f80-g4h5-7c62-145g-984gh05i5e7g', 'nutrition.food_name_salmon_raw', 208, 20, 0, 13, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('6e1f0g90-h5i6-8d73-256h-095hi16j6f8h', 'nutrition.food_name_boiled_egg', 78, 6, 1, 5, 'QUANTITY', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('7f2g1h00-i6j7-9e84-367i-106ij27k7g9i', 'nutrition.food_name_peanut_butter', 588, 25, 20, 50, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('8g3h2i10-j7k8-0f95-478j-217jk38l8h0j', 'nutrition.food_name_tofu', 76, 8, 2, 5, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('9h4i3j20-k8l9-1g06-589k-328kl49m9i1k', 'nutrition.food_name_greek_yogurt', 59, 10, 4, 0, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('0i5j4k30-l9m0-2h17-690l-439lm50n0j2l', 'nutrition.food_name_almonds', 579, 21, 21, 49, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('1j6k5l40-m0n1-3i28-701m-540mn61o1k3m', 'nutrition.food_name_broccoli_boiled', 35, 3, 7, 0, 'GRAM', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('2k7l6m50-n1o2-4j39-812n-651no72p2l4n', 'nutrition.food_name_olive_oil', 126, 0, 0, 14, 'ML', 15.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('3l8m7n60-o2p3-5k40-923o-762op83q3m5o', 'nutrition.food_name_orange_juice', 45, 1, 10, 0, 'ML', 100.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('4m9n8o70-p3q4-6l51-034p-873pq94r4n6p', 'nutrition.food_name_bun_bo_hue', 440, 25, 50, 15, 'SERVING', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('5n0o9p80-q4r5-7m62-145q-984qr05s5o7q', 'nutrition.food_name_hu_tieu', 390, 20, 55, 10, 'SERVING', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('6o1p0q90-r5s6-8n73-256r-095rs16t6p8r', 'nutrition.food_name_mi_quang', 500, 25, 60, 18, 'SERVING', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('7p2q1r00-s6t7-9o84-367s-106st27u7q9s', 'nutrition.food_name_banh_cuon', 350, 10, 50, 12, 'SERVING', 1.0, 0);
INSERT INTO foods (id, name, cal, p, c, f, unit, amount, is_deleted) VALUES ('8q3r2s10-t7u8-0p95-478t-217tu38v8r0t', 'nutrition.food_name_xoi_man', 480, 15, 70, 15, 'SERVING', 1.0, 0);