"""Compile editable, flattened SVG sources into synchronous Flutter path data.

Usage: python tool/generate_body_map_paths.py [--check]
No third-party packages required. Unknown IDs and transforms fail closed.
"""
import sys
import re
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'lib/features/profile/presentation/components/bodymap/generated'
MUSCLE_GROUPS = {
    'front': {'upper-chest', 'middle-chest', 'lower-chest', 'abs', 'obliques',
              'quads', 'biceps', 'triceps', 'forearms', 'front-delts', 'side-delts',
              'adductors', 'traps', 'calves', 'neck'},
    'back': {'lats', 'upper-back', 'lower-back', 'traps', 'rear-delts', 'triceps',
             'forearms', 'glutes', 'quads', 'hamstrings', 'calves', 'adductors',
             'abductors', 'neck'},
}


def generate(gender):
    lines = ['// GENERATED by tool/generate_body_map_paths.py. Edit SVG sources instead.',
             "import '../../../../../../core/database/enums.dart';",
             f'class {gender.title()}BodyPaths {{']
    for side in ['front', 'back']:
        root = ET.parse(ROOT/f'assets/svg/bodymap/{gender}_{side}.svg').getroot()
        if root.attrib.get('viewBox') != '0 0 1900 3500':
            raise ValueError('All views must use the shared viewport')
        if any('transform' in node.attrib for node in root.iter()):
            raise ValueError('Flatten SVG transforms before generation')
        identified = [n for n in root.iter() if 'id' in n.attrib]
        nodes = {n.attrib['id']:n for n in root.iter() if 'id' in n.attrib}
        if len(nodes) != len(identified):
            raise ValueError('Duplicate SVG IDs')
        expected_layers = {'hair-back', 'body-base', 'muscle-heatmap',
                           'skin-lines', 'body-outline', 'hair-front'}
        if {n.attrib.get('id') for n in root} != expected_layers:
            raise ValueError('Unexpected or missing layer IDs')
        expected_groups = MUSCLE_GROUPS[side]
        if {n.attrib['id'] for n in nodes['muscle-heatmap']} != expected_groups:
            raise ValueError('Muscle taxonomy must match the original source')
        for node in root.iter():
            if node.tag.rsplit('}', 1)[-1] not in {'svg', 'g', 'path'}:
                raise ValueError('Convert shapes to paths before generation')
            if 'd' in node.attrib and not re.fullmatch(r'[MmLlHhVvCcSsQqTtAaZz0-9eE+.,\s-]*', node.attrib['d']):
                raise ValueError('Invalid SVG path data')
        if nodes['body-base'].attrib['d'] != nodes['body-outline'].attrib['d']:
            raise ValueError('Body base and outline must share geometry')
        for id, field in [('body-outline','Border'),('skin-lines','Skin'),('hair-back','HairBack'),('hair-front','HairFront')]:
            data = nodes[id].attrib['d']
            lines.append(f"  static const String {side}{field} = '{data}';")
        lines.append(f'  static const Map<MuscleGroup, String> {side}Muscles = {{')
        for group in nodes['muscle-heatmap']:
            name = group.attrib['id'].upper().replace('-','_')
            data = ' '.join(n.attrib['d'] for n in group if n.tag.endswith('path'))
            if not data:
                raise ValueError(f'Empty muscle {name}')
            lines.append(f"    MuscleGroup.{name}: '{data}',")
        lines.append('  };')
    lines.append('}')
    return '\n'.join(lines)+'\n'


if __name__ == '__main__':
    OUT.mkdir(parents=True,exist_ok=True)
    results = {gender: generate(gender) for gender in ['male', 'female']}
    for gender, result in results.items():
        dest = OUT/f'{gender}_body_paths.dart'
        if '--check' in sys.argv:
            if not dest.exists() or dest.read_text(encoding='utf-8') != result:
                raise SystemExit(f'Stale generated file: {dest}')
        else:
            dest.write_text(result,encoding='utf-8')
    print('Bodymap sources and generated paths are synchronized.')
